pipeline {
    agent any
    stages {
        stage('Pull from git'){
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/gaurav-lucky/JobPortal_Project.git'
             }
        }
        stage('Build') {
            steps {
           sh 'mvn compile test package'
            }
        }
    }
}
